/* 
Tên: Nguyễn Khánh Trung
Lớp: 24TTH002
MSSV: 24T01010 */
const books = [
    {
        id: "nhungnguoikhonkho",
        name: "Những người khốn khổ",
        tacgia: "Victor Hugo",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/nhungnguoikhonkho/nhungnguoikhonkho_1.jpg",
        imgCount: 3,
        mota: "Những người khốn khổ là tiểu thuyết của văn hào Pháp Victor Hugo, được xuất bản năm 1862. Tác phẩm được đánh giá là một trong những tiểu thuyết nổi tiếng nhất của nền văn học thế giới thế kỷ 19.",
        gia: 1000000,
    },
    {
        id: "thepdatoitheday",
        name: "Thép đã tôi thế đấy",
        tacgia: "Nikolai Alekseyevich Ostrovsky",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/thepdatoitheday/thepdatoitheday_1.jpg",
        imgCount: 3,
        mota: "Tiểu thuyết Thép đã tôi thế đấy của Nikolai Ostrovsky là một tác phẩm kinh điển của văn học Nga nói riêng và văn học cách mạng nói chung, đã trở thành nguồn cảm hứng cho nhiều thế hệ độc giả.",
        gia: 1000000,
    },
    {
        id: "bogia",
        name: "Bố già",
        tacgia: "Mario Puzo",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/bogia/bogia_1.jpg",
        imgCount: 3,
        mota: "Bố già là tên một cuốn tiểu thuyết nổi tiếng của nhà văn người Mỹ gốc Ý Mario Puzo, được nhà xuất bản G. P. Putnam's Sons xuất bản lần đầu vào năm 1969. Tác phẩm là câu chuyện về một gia đình mafia gốc Sicilia tại Mỹ, được một nhân vật gọi là Bố già Don Vito Corleone tạo lập và lãnh đạo.",
        gia: 1000000,
    },
    {
        id: "cuontheochieugio",
        name: "Cuốn theo chiều gió",
        tacgia: "Margaret Mitchell",
        theloai: "Tâm Lý",
        image: "hinhanh/cuontheochieugio/cuontheochieugio_1.jpg",
        imgCount: 3,
        mota: "Cuốn theo chiều gió, xuất bản lần đầu năm 1936, là một cuốn tiểu thuyết tình cảm của Margaret Mitchell, người đã giành giải Pulitzer với tác phẩm này năm 1937. Câu chuyện được đặt bối cảnh tại Georgia và Atlanta, miền Nam Hoa Kỳ trong suốt thời kì nội chiến và thời tái thiết.",
        gia: 1000000,
    },
    {
        id: "truyenloaivat",
        name: "Truyện loài vật",
        tacgia: "Ernest Thompson Seton",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/truyenloaivat/truyenloaivat_1.jpg",
        imgCount: 3,
        mota: "Là tác phẩm trong đó lần đầu tiên chim và thú được đưa lên làm nhân vật chính thực sự, Truyện loài vật gồm các câu chuyện cảm động mô tả chân thực, chính xác về hành vi, đời sống của các con vật trong tự nhiên.",
        gia: 1000000,
    },
    {
        id: "nguaoyeudau",
        name: "Ngựa ô yêu dấu",
        tacgia: "Anna Sewell",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/nguaoyeudau/nguaoyeudau_1.jpg",
        imgCount: 3,
        mota: "Được xem là câu chuyện nổi tiếng nhất mọi thời đại về loài vật, Ngựa ô yêu dấu kể lại những cuộc phiêu lưu, những nỗi đắng cay lẫn niềm hạnh phúc của Black Beauty, một chú ngựa ô đẹp mã, trung thành và dũng cảm. Khi bị ông chủ buộc lòng bán đi, Black Beauty phải từ bỏ cuộc sống êm ấm, dễ chịu để bước vào đoạn đời cực nhọc, bị đối xử tàn nhẫn.",
        gia: 1000000,
    },
    {
        id: "hiepsithanhchien",
        name: "Hiệp sĩ thánh chiến",
        tacgia: "Henryk Sienkiewicz",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/hiepsithanhchien/hiepsithanhchien_1.jpg",
        imgCount: 3,
        mota: "Hiệp Sĩ Thánh Chiến là một thiên tiểu thuyết lịch sử đồ sộ, kết tinh giữa tinh thần anh hùng ca, chiều sâu nhân văn và niềm tự hào dân tộc mãnh liệt.",
        gia: 1000000,
    },
    {
        id: "nanhtrang",
        name: "Nanh trắng",
        tacgia: "Jack London",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/nanhtrang/nanhtrang_1.jpg",
        imgCount: 3,
        mota: "Nanh Trắng là một câu truyện về cuộc hành trình của một con chó sói lai chó nhà để trở thành một kẻ được khai hóa trong lãnh thổ Yukon của Canada trong thời kỳ đổ xô đi tìm vàng Klondike cuối thế kỷ 19.",
        gia: 1000000,
    },
    {
        id: "onggiavabienca",
        name: "Ông già và biển cả",
        tacgia: "Ernest Hemingway",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/onggiavabienca/onggiavabienca_1.jpg",
        imgCount: 3,
        mota: "Lấy bối cảnh một làng chài ở La Habana, tác phẩm kể về cuộc chiến đấu đơn độc của ông lão Santiago với con cá kiếm hùng dũng và đàn cá mập hung tợn giữa lòng đại dương.",
        gia: 1000000,
    },
    {
        id: "hoangtube",
        name: "Hoàng tử bé",
        tacgia: "Antoine de Saint-Exupéry",
        theloai: "Thiếu Nhi",
        image: "hinhanh/hoangtube/hoangtube_1.jpg",
        imgCount: 3,
        mota: "Kể về một hoàng tử nhỏ cô đơn từ tiểu tinh cầu xa xôi viếng thăm rồi lại lìa xa Trái Đất, Hoàng tử bé được xem là một trong những tác phẩm thơ mộng nhất của mọi thời đại.",
        gia: 1000000,
    },
    {
        id: "sherlockholmes",
        name: "Sherlock Holmes",
        tacgia: "Sir Arthur Conan Doyle",
        theloai: "Trinh Thám",
        image: "hinhanh/sherlockholmes/sherlockholmes_1.jpg",
        imgCount: 3,
        mota: "Cái tên Sherlock Holmes đã quen thuộc khắp thế giới tới mức một người dù có thể chưa hề đọc truyện về nhà thám tử này nhưng chỉ cần nghe tên cũng biết anh ta là ai. Sherlock Holmes đã trở thành một biểu tượng của văn hóa đại chúng toàn cầu. Khác với những nhân vật thần tượng chỉ vang bóng một thời, Sherlock Holmes kể từ khi xuất hiện lần đầu tiên năm 1887 qua sáng tạo của Sir Arthur Conan Doyle vẫn sống mãi qua ba thế kỉ.",
        gia: 1000000,
    },
    {
        id: "dinhgiohu",
        name: "Đỉnh gió hú",
        tacgia: "Emily Bronte",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/dinhgiohu/dinhgiohu_1.jpg",
        imgCount: 3,
        mota: "Đỉnh gió hú là tiểu thuyết duy nhất của nữ nhà văn Emily Brontë, được xuất bản lần đầu năm 1847 dưới bút danh Ellis Bell.",
        gia: 1000000,
    },
    {
        id: "HCM_tieusubanghinh",
        name: "Hồ Chí Minh- tiểu sử bằng hình",
        tacgia: "Công ty Cổ phần Văn hóa Đông A",
        theloai: "Tư liệu",
        image: "hinhanh/HCM_tieusubanghinh/HCM_tieusubanghinh_1.jpg",
        imgCount: 3,
        mota: "Chủ tịch Hồ Chí Minh là người đặt nền móng và khai sinh ra nước Việt Nam Dân chủ Cộng hòa – nhà nước dân chủ nhân dân đầu tiên ở Đông Nam Á. Với tầm vóc của một nhà cách mạng kiệt xuất, nhà tư tưởng và văn hóa lớn, Chủ tịch Hồ Chí Minh đã dẫn dắt dân tộc Việt Nam giành được độc lập và xây dựng nền tảng cho một quốc gia hiện đại.",
        gia: 1000000,
    },
    {
        id: "khuvuonbimat",
        name: "Khu vườn bí mật",
        tacgia: "Frances H Burnett",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/khuvuonbimat/khuvuonbimat_1.jpg",
        imgCount: 3,
        mota: "Mary Lennox, một cô bé mồ côi, cáu kỉnh, không ai ưa, tới sống tại nhà ông bác ở vùng đồng hoang Yorkshire, nước Anh, nơi có rất nhiều bí mật đang đợi cô.",
        gia: 1000000,
    },
    {
        id: "tamquocdiennghia",
        name: "Tam quốc diễn nghĩa",
        tacgia: "La Quán Trung",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/tamquocdiennghia/tamquocdiennghia_1.jpg",
        imgCount: 3,
        mota: "Tam quốc diễn nghĩa, nguyên tên là Tam quốc chí thông tục diễn nghĩa, là một cuốn tiểu thuyết dã sử về lịch sử Trung Quốc được nhà văn La Quán Trung viết vào thế kỷ 14. Tiểu thuyết có nội dung kể về một thời kỳ hỗn loạn trong lịch sử Trung Hoa là giai đoạn cuối thời Đông Hán và sau đó là Tam Quốc.",
        gia: 1000000,
    },
    {
        id: "tayduky",
        name: "Tây du ký",
        tacgia: "Ngô Thừa Ân",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/tayduky/tayduky_1.jpg",
        imgCount: 3,
        mota: "Tây Du Ký, là một trong những tác phẩm kinh điển trong văn học Trung Hoa.",
        gia: 1000000,
    },
    {
        id: "truyencogrim",
        name: "Truyện cổ Grim",
        tacgia: "Jacob & Wilhelm Grimm",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/truyencogrim/truyencogrim_1.jpg",
        imgCount: 3,
        mota: "Truyện kể gia đình cho trẻ em (tiếng Đức: Kinder- und Hausmärchen) là một tập hợp các truyện cổ tích tiếng Đức lần đầu tiên được xuất bản năm 1812 bởi Anh em nhà Grimm, Jacob và Wilhelm. Bộ truyện này thường được biết tới đến với tên gọi Truyện cổ Grimm ",
        gia: 1000000,
    },
    {
        id: "tamhoncaothuong",
        name: "Tâm hồn cao thượng",
        tacgia: "Edmondo De Amicis",
        theloai: "Tiểu Thuyết",
        image: "hinhanh/tamhoncaothuong/tamhoncaothuong_1.jpg",
        imgCount: 3,
        mota: "Enrico Bottini, một cậu bé mười tuổi người Ý, trong suốt năm học lớp ba đã đều đặn ghi lại những câu chuyện mà em ấn tượng. Từ những việc làm của thầy cô giáo, bạn bè, hàng xóm cho đến những câu chuyện được đọc trên lớp, những bức thư của mẹ cha hay những sự kiện trên đường phố, tất cả đều được ghi vào một cuốn nhật ký. Với Enrico, mỗi câu chuyện ấy là một bài học về tình thầy trò, bè bạn và cha con… về sự yêu thương, lòng trắc ẩn và tình yêu nước… Tất cả tạo nên một tác phẩm xúc động lòng người.",
        gia: 1000000,
    },
    {
        id: "gauguin",
        name: "Gauguin",
        tacgia: "George Roddam",
        theloai: "Khoa Học",
        image: "hinhanh/gauguin/gauguin_1.jpg",
        imgCount: 3,
        mota: "Đây là Gauguin kể về cuộc đời và sự nghiệp của họa sỹ Hậu Ấn tượng vĩ đại người Pháp Gauguin",
        gia: 800000,
    },
    {
        id: "tomsawyer",
        name: "Những cuộc phiêu lưu của Tom Sawyer",
        tacgia: "Mark Twain",
        theloai: "Thiếu nhi",
        image: "hinhanh/tomsawyer/tomsawyer_1.jpg",
        imgCount: 3,
        mota: "Với bản tính hiếu động, Tom Sawyer không lúc nào chịu yên. Chú quậy phá đủ trò tai quái từ trốn học, lừa bạn bè sơn hàng rào, cầm đầu lũ trẻ đánh nhau cho đến chữa mụn cóc ngoài nghĩa trang, “đính hôn” với cô bạn Becky, hay ra đảo sống đời cướp biển. Thế nhưng, cũng trong những chuyến phiêu lưu ấy, Tom và bạn bè đã khám phá ra một vụ giết người, phá tan âm mưu của toán cướp, cứu mạng Becky, tìm được kho báu và trở thành anh hùng của thị trấn.",
        gia: 1000000,
    },
    {
        id: "xahoi",
        name: "Xã hội học",
        tacgia: "DK",
        theloai: "Xã Hội",
        image: "hinhanh/xahoi/xahoi_1.jpg",
        imgCount: 3,
        mota: "Liệu sự phân chia trong xã hội có thể bị xóa bỏ? Điều gì dẫn dắt người ta đến con đường phạm tội? Internet đã biến đổi những mối quan hệ của chúng ta như thế nào? Suốt lịch sử, con người luôn đặt ra những câu hỏi về cách tổ chức xã hội của mình - và xã hội học đã mang đến những lời giải mà nay vẫn tiếp tục định hình thế giới ta đang sống.",
        gia: 1000000,
    },
    {
        id: "lichsu",
        name: "Combo 2 cuốn: Lịch sử Việt Nam bằng hình ",
        tacgia: "ST",
        theloai: "Lịch Sử",
        image: "hinhanh/lichsu/lichsu_1.jpg",
        imgCount: 3,
        mota: "Lịch sử Việt Nam bằng hình phác họa bức chân dung toàn cảnh về quá trình dựng nước và giữ nước, xuyên suốt từ thời xuất hiện các cư dân cổ xưa đầu tiên trên lãnh thổ cho đến khi hình thành một quốc gia hiện đại như ngày nay.",
        gia: 1000000,
    },
    {
        id: "dienrohaythanthanh",
        name: "Điên rồ hay thần thánh",
        tacgia: "José Echegaray",
        theloai: "Tư Liệu",
        image: "hinhanh/dienrohaythanthanh/dienrohaythanthanh_1.jpg",
        imgCount: 3,
        mota: "Nói ví von theo lời nhà phê bình Mérimée, cuộc đời của José Echegaray chính là một vở kịch có ba hồi: Hồi I. Nhà nghiên cứu khoa học; Hồi II. Nhà chính khách; Hồi III. Nhà soạn kịch.",
        gia: 1000000,
    },
    {
        id: "khongnoinuongtua",
        name: "Không nơi nương tựa",
        tacgia: "Dave Pelzer",
        theloai: "Tự Truyện",
        image: "hinhanh/khongnoinuongtua/khongnoinuongtua_1.jpg",
        imgCount: 3,
        mota: "Không Nơi Nương Tựa là câu chuyện thật của chính tác giả, kể về thời thơ ấu bị vùi dập đau thương của mình - một trong những trường hợp hắt hủi và bạo hành trẻ em nghiêm trọng nhất lịch sử bang California, Hoa Kỳ.",
        gia: 700000,
    },


];
